package view;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import java.awt.*;

public class CurriculumViewer extends JFrame {


    private JPanel mainPane;
    private JTextArea textInfo;
    private JTree packages;
    private JComboBox comboBox;
    private static final String FILE = "FILE";
    private static final String EXIT = "EXIT";
    private static final String IMPORT_FROM_FILE = "IMPORT XML FROM FILE";


    public CurriculumViewer() {
        $$$setupUI$$$();
        setTitle("CurriculmViewer");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(getMainPane());
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
        packages.setModel(null);
        makeComboBox();
    }

    private void makeComboBox() {
        comboBox.addItem(FILE);
        comboBox.addItem(EXIT);
        comboBox.addItem(IMPORT_FROM_FILE);
    }




    public JPanel getMainPane() {
        return mainPane;
    }

    public void setMainPane(JPanel mainPane) {
        this.mainPane = mainPane;
    }

    public JTextArea getTextInfo() {
        return textInfo;
    }

    public void setTextInfo(JTextArea textInfo) {
        this.textInfo = textInfo;
    }

    public JTree getPackages() {
        return packages;
    }

    public void setPackages(JTree packages) {
        this.packages = packages;
    }

    public JComboBox getComboBox() {
        return comboBox;
    }

    public void setComboBox(JComboBox comboBox) {
        this.comboBox = comboBox;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPane.setAlignmentX(1.0f);
        mainPane.setAlignmentY(1.0f);
        mainPane.setBackground(new Color(-4141582));
        mainPane.setDoubleBuffered(false);
        mainPane.setEnabled(false);
        mainPane.setMaximumSize(new Dimension(600, 400));
        mainPane.setMinimumSize(new Dimension(600, 400));
        mainPane.setOpaque(true);
        mainPane.setPreferredSize(new Dimension(600, 400));
        mainPane.setRequestFocusEnabled(false);
        mainPane.setVerifyInputWhenFocusTarget(true);
        textInfo = new JTextArea();
        mainPane.add(textInfo, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        packages = new JTree();
        mainPane.add(packages, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        comboBox = new JComboBox();
        mainPane.add(comboBox, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
